<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>FederationCompanion</RootNamespace>
    <AssemblyName>FederationCompanion</AssemblyName>
    <Version>0.0.136</Version>
    <AssemblyVersion>0.0.136.0</AssemblyVersion>
    <FileVersion>0.0.136.0</FileVersion>
    <UserSecretsId>federation-companion</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FederationCompanion.Tests" />
  </ItemGroup>

</Project>
